### ISSUE TITLE
movieQA dataset [qa.json]

### ISSUE THREAD

**Issue by jacobssy** [chun5212021202/ACM-Net#1]
Hi,
Thanks for you contribution, I have downloaded the movie stories include video clips,plot,subtitle... but the qa.json file is lost. and the movieqa dataset is down for maintenance currently. May you provide the qa.json ? I wish I could get your response 👍

**Comment by liangnaiyao** [comment]
https://github.com/BinbinBian/MovieQA-1/tree/master/data

**Comment by liangnaiyao** [comment]
Hello, movieQA dataset [qa.json] is above. May you have movieQA dataset [IMDB_KEY.split.wiki]. I wish I could get your response, too.

**Comment by jacobssy** [comment]
@xiaosage24k Thank you ! I do not find the .split.wiki ... I get files  from my friend... only subtitle and video..

**Comment by Psjs** [comment]
> @xiaosage24k Thank you ! I do not find the .split.wiki ... I get files from my friend... only subtitle and video..

Could you please provide the complete movieQA Dataset? I really need this. Thank you very much
